- name: declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare variable in another file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name:  access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare variable at task level
  hosts: all
  connection: local
  tasks:
    - name: declare and access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: play.example.com

- name: declare variable from inventory file
  hosts: all
  connection: local
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: access fact
  hosts: all
  connection: local
  tasks:
    - name: access facts
      ansible.builtin.debug:
        msg: ansible host name == {{ansible_fqdn}}


- name: register a variable
  hosts: all
  connection: local
  tasks:
    - name: run shall a command
      ansible.builtin.shell: uptime
      register: out

    - name: print out
      ansible.builtin.debug:
        msg: "{{out}}"