- name: declare variable at play level
  hosts: all
  connection: local
  vars:
    url: play.example.com
  tasks:
    - name: access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
