- name: demo on conditions
  hosts: all
  vars:
    a: 100
    b: true
  tasks:
    - name: string conditions
      debug:
        msg: fruit name is apple
      when: fruit_name == "apple"
    - name: numerical conditions
      debug:
        msg: a is greater than 10
      when: a > 10
    - name: boolean condition
      debug:
        msg: b is true
      when: b
